// <auto-generated />
using System;
using ArthurTavares.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArthurTavares.Migrations
{
    [DbContext(typeof(DbConfig))]
    partial class DbConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArthurTavares.Models.Filme", b =>
                {
                    b.Property<int>("Id_filme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao_filme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Lancamento_filme")
                        .HasColumnType("date");

                    b.Property<string>("Titulo_filme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_filme");

                    b.HasIndex("Id_usuario");

                    b.ToTable("filmes");
                });

            modelBuilder.Entity("ArthurTavares.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_usuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ArthurTavares.Models.Filme", b =>
                {
                    b.HasOne("ArthurTavares.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
